### PR TITLE
cmake build rework

### PR DESCRIPTION
**Pull request by dabrain34**
Factorize the build of vk_video_samples to one CMakefile containing the definitions for both decoder and encoder
project.
Can now enable disable the build of encoder/decoder by a CMake option.

### CODE REVIEW

**Comment by dabrain34** [comment]
@zlatinski

**Review by zlatinski — APPROVED** [review]
LGTM - Thanks for the improvements, Stephan!

**Review by zlatinski — COMMENTED** [review]
I need some time to review these cmakefile changes.  Thank you, Stephan!

**Review by zlatinski — APPROVED** [review]
I think this one looks good, too. Before I merge this change, have you tested this on Windows, Stephan?

**Comment by dabrain34** [comment]
I just tested today on Windows and unfortunately the build is failing. Investigating..
Have you been able to discuss to enable a CI on this repository ? It would help to track this kind of regression. :)

**Review by zlatinski — APPROVED** [review]
LGTM, thanks for the change!

**Review by zlatinski — APPROVED** [review]
LGTM, thanks for the change!

**Review by zlatinski — APPROVED** [review]
LGTM, thanks for the change!

**Review by zlatinski — APPROVED** [review]
LGTM, thanks for the change!

**Review by zlatinski — APPROVED** [review]
LGTM, thanks for the change!

**Comment by dabrain34** [comment]
I'm wondering if we would make sense to have a vkCodecUtils static library with:

- VkCodecUtils/VulkanDeviceContext.cpp
- VulkanDeviceMemoryImpl.cpp
...

What do you think @zlatinski ?

**Pull request merged**
