### PR TITLE
video_encoder: generate 15 P frames per GOP

### PR DESCRIPTION
**Pull request by clemy**
Added a very simple generation of P frames to the encoder example.
1 IDR, 15 P (each referencing the previous I or P frame only), 1 IDR, ...
Tested on RTX3070
Maybe you are interested in this change. I am quite new to this area, so maybe it is not useful at all.

### CODE REVIEW

**Comment by zlatinski** [comment]
Thank you, Bernhard, for the change. We are in the process of changing the Vulkan video encode APIs - I'll make sure to review and integrate your change after these changes are done.

**Comment by clemy** [comment]
Hi,
thanks for considering the change. I also made adaptations to the latest Vulkan API revision (for latest Nvidia Beta Driver), but did not code the SPS/PPS generation, so it is not ready for use. But if you are interested: https://github.com/clemy/vk_video_samples/commits/rev8_rev10_update

**Comment by zlatinski** [comment]
> Hi, thanks for considering the change. I also made adaptations to the latest Vulkan API revision (for latest Nvidia Beta Driver), but did not code the SPS/PPS generation, so it is not ready for use. But if you are interested: https://github.com/clemy/vk_video_samples/commits/rev8_rev10_update

BTW: Marcin also has updated the encoder's API at https://github.com/neurotok/vk_video_samples

**Comment by zlatinski** [comment]
Hi Bernhard,
Thank you for providing these fixes. We have changed the video encode sample app architecture, and these changes are not required anymore.

I find your sample at https://github.com/clemy/vulkan-video-encode-simple very easy to follow and is great for somebody who wants to start learning the Vulkan video encode APIs.

Please continue with the great work you are doing on Vulkan video.

Best Regards!

**Pull request closed without merging**
